apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: casm-fit-ce-mnni-cubic-
spec:

  entrypoint: job

  arguments:
    parameters:
    - name: git-repo
      value: "git@github.com:DenisKramer/ce_MnNi_cubic.git"
    - name: cluster
      value: "iridis5"

  volumes:
  - name: ssh
    secret:
        secretName: "{{workflow.parameters.cluster}}-login"
        defaultMode: 256

  entrypoint: job

  templates:

  # Main workflow template
  - name: job
    steps:
    - - name: fit
        template: fit-eci
        arguments:
          parameters:
          - name: fitdir
            value: "{{item.dir}}"
          - name: filter
            value: "{{item.filter}}"
        withItems:
        - { dir: 'fit_1', filter: 'is_calculated' }
        - { dir: 'fit_2', filter: 'and(is_calculated,le(comp(a),0.5))' }
        - { dir: 'fit_3', filter: 'and(is_calculated,ge(comp(a),0.5))' }          
    
    - - name: update
        template: update-repo

  # Leafs

  - name: clone-repo
    inputs:
      parameters:
      - name: repo
    script:
      image: alpine/git
      command: [ "/bin/sh" ]
      env:    
      - name: GIT_SSH_COMMAND
        value:  ssh -i /ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      volumeMounts:
      - name: repo
        mountPath: /data
      - name: ssh
        mountPath: /ssh
      source: |
        git clone {{inputs.parameters.repo}} /data/repo

  - name: update-repo
    retryStrategy:
      limit: 5
    inputs:
      parameters:
      - name: fitdir
      artifacts:
      - name: fit-folder
        path: /data/fit-folder
      - name: repo
        path: /data/repo
        git:
          repo: "{{workflow.parameters.git-repo}}"
          sshPrivateKeySecret:
            name: "{{workflow.parameters.cluster}}-login"
            key: id_rsa
    script:
      image: alpine/git
      command: [ "/bin/sh" ]
      volumeMounts:
      - name: ssh
        mountPath: /ssh
      env:
      - name: GIT_SSH_COMMAND
        value:  ssh -i /ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      source: |
        cd /data/repo
        cp -r /data/fit-folder {{inputs.parameters.fitdir}}
        git config user.email "no-reply@kramergroup.science"
        git config user.name "Argo Workflow Bot"
        git add {{inputs.parameters.fitdir}}
        git commit -m "Added result from workflow {{workflow.name}}"
        git push

  - name: fit-eci
    inputs:
      parameters:
      - name: fitdir
      - name: filter       
    steps:
    - - name: fit
        template: train-eci
        arguments:
          parameters:
          - name: fitdir
            value: "{{inputs.parameters.fitdir}}"
          - name: filter
            value: "{{inputs.parameters.filter}}"
    - - name: update
        template: update-repo
        arguments:
          parameters:
          - name: fitdir
            value: "{{inputs.parameters.fitdir}}"    
          artifacts:
          - name: fit-folder
            from: "{{steps.fit.outputs.artifacts.fit-folder}}" 

  - name: train-eci
    inputs:
      parameters:
      - name: fitdir
      - name: filter
      artifacts:
      - name: repo
        path: /data/repo
        git:
          repo: "{{workflow.parameters.git-repo}}"
          sshPrivateKeySecret:
            name: "{{workflow.parameters.cluster}}-login"
            key: id_rsa
    outputs:
      artifacts:
      - name: fit-folder
        path: "/data/repo/{{inputs.parameters.fitdir}}"
    script:
      image: kramergroup/casm:condo-latest
      command: ["/bin/bash"]
      volumeMounts:
      - name: repo
        mountPath: /data
      source: |
        mkdir -p /data/repo/{{inputs.parameters.fitdir}}
        cd /data/repo/{{inputs.parameters.fitdir}}
        rm -rf *
        echo "Selecting training set with filter {{inputs.parameters.filter}}"
        casm select -c CALCULATED --set '{{inputs.parameters.filter}}' -o train --force
        echo "Creating new ECI setting {{inputs.parameters.fitdir}}"
        casm settings --new-property formation_energy
        casm settings --new-eci {{inputs.parameters.fitdir}}
        
        if [ ! -f fit_ga.json ]; then
          casm learn --exGeneticAlgorithm > fit_ga.json
        fi
        echo "Fitting ECIs ..."
        casm learn -s fit_ga.json > fit.out 
        casm learn -s fit_ga.json --select 0
        casm query -c train -k 'comp(a) formation_energy clex()' -o summary.dat


